### PR TITLE
Move defopt to package

### PR DESCRIPTION
**Pull request by macdems**
As the module grows, I think this is not elegant to put separate modules starting with _, but it should be combined in a package.

### CODE REVIEW

**Comment by anntzer** [comment]
Actually, I see that napoleon upstream just merged https://github.com/sphinx-contrib/napoleon/pull/36, fixing the 3.6 issue.  Let's try to make them release that first, in which case we can go back to having napoleon as a dependency (which is my preferred approach).

**Comment by macdems** [comment]
Ok, however still it would be much neater not to create an independent module `_defopt_version`, but collect it into a package.

**Comment by anntzer** [comment]
That part I'll probably completely get rid of and replace by https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime.

**Comment by macdems** [comment]
> That part I'll probably completely get rid of and replace by https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime.

Good idea!

**Comment by anntzer** [comment]
Done.
I think the best thing you could do now is to prod the sphinxcontrib.napoleon maintainer for a new release :-)

**Pull request closed without merging**
