### PR TITLE
Switch ownership and license.

### PR DESCRIPTION
**Pull request by anntzer**
attn @evanunderscore

### CODE REVIEW

**Comment by evanunderscore** [comment]
Approved. Thanks!

**Comment by twosigmajab** [comment]
Hi @anntzer, the [most recent release (5.1.0 from about a year ago)](https://pypi.org/project/defopt/) is still GPL. Interested to consider defopt for a project at work (defopt looks great!), and a new release (with this license change) would make that possible. Were you thinking of cutting a new release any time soon? Thanks for maintaining defopt!

**Comment by anntzer** [comment]
I can cut a new release.  Can you please confirm first that master works for you?

**Comment by anntzer** [comment]
@twosigmajab Any news as to whether master works for you?

**Comment by twosigmajab** [comment]
Sorry for the delay, @anntzer, things got busy here and I haven't had a chance to test master yet. Still interested in seeing a new release of defopt, but if you'd like more confidence from user testing of master before releasing, are there any existing/more-established users you could ask?

**Comment by anntzer** [comment]
Not that I know of, but I'm not in a particular hurry to get a new release out anyways (basically unless there's demand for it :)).

**Comment by anntzer** [comment]
I released v6.0 to PyPI.

**Pull request merged**
